require('dotenv').config();
require('./config/database');

const Wine = require('./models/wine.js');

(async function() {
    await Wine.deleteMany({});
    const wines = await Wine.create([
        {name: 'Whiskerlicious Red', image: 'https://images.unsplash.com/photo-1609951651569-52005958f960?auto=format&fit=crop&q=80&w=2864&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', genre: 'Merlot', taste: 'A comforting bear hug with a playful oregano twist.', alcohol_content: 14.7, price: 67.85, allergens: 'Contains sulfites and tea tree beard oil.', conservation: 'Keep in a dry place away from the light and your enemies. Avoid abrupt temperature changes.', description: 'It\'s like a cozy bear hug for your taste buds, with a mischievous twist of oregano that\'ll have you purring with delight!', pairing: 'Combine this with a Classic PB&J Sandwich because who needs caviar when you have grape jelly, right?'},
        {name: 'Grapefully Bearded', image: 'https://images.unsplash.com/photo-1606767208159-1a5fb0a87841?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3087&q=80', genre: 'Sauvignon Blanc', taste: 'Sip the essence of Mediterranean grapes and a gnome\'s oregano magic.', alcohol_content: 18.2, price: 63.44, allergens: 'Contains sulfites and maybe a little bit of fertilizer.', conservation: 'Keep in a dry place away from the light. Avoid abrupt temperature changes. No cats.', description: 'Our Oregano Obsession is like a secret love affair between your palate and a Mediterranean garden gnome.', pairing: 'Combine this with Sriracha Ice Cream for a spicy-sweet sensation that\'ll make you question your dessert choices.'},
        {name: 'Playful Pinot Grigio', image: 'https://images.unsplash.com/photo-1556395650-b30c53b4ff77?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2624&q=80', genre: 'Pinot Grigio', taste: 'Playful and zesty, like a grape water balloon fight with a citrus twist.', alcohol_content: 14.2, price: 72.88, allergens: 'Contains sulfites but never random pieces of plastic.', conservation: 'Keep in a dry place away from the light. Avoid abrupt temperature changes. No tapping on the glass, you will scare the fish.', description: 'As mischievous as a grape in a game of hide-and-seek, it dances on your palate like a whimsical water balloon fight, with a hint of zesty lemon-lime antics.', pairing: 'Combine with a cheese platter and a side of cheesy jokes.'},
        {name: 'Barrel of Laughs Pinot Noir', image: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3087&q=80', genre: 'Pinot Noir', taste: 'A comedic burst of ripe cherries and witty oak.', alcohol_content: 15.7, price: 84.23, allergens: 'Contains sulfites and the vibe of oregano.', conservation: 'Keep in a dry place away from the light. Avoid abrupt temperature changes. It won\'t like the sound of country music on Tuesdays.', description: 'This wine is like a stand-up comedian in a bottle. It starts with a smooth entrance, then hits your taste buds with a punchline of ripe cherries and a twist of witty oakiness, leaving you in stitches of delight.', pairing: 'Combine with a pizza with the silliest and most unexpected toppings you can think of, like gummy bears or pickles. Enjoy the absurdity with your wine.'},
        {name: 'Beard-o-Vino', image: 'https://images.unsplash.com/photo-1601924376620-fac275e571b3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3088&q=80', genre: 'Sauvignon Blanc', taste: 'Refreshing breeze of crisp apple and whimsical oregano.', alcohol_content: 16.3, price: 72.96, allergens: 'Contains sulfites and sometimes the smell of peanut butter.', conservation: 'Keep in a dry place away from the light. Cradle often.', description: 'A white wine that\'s as light and airy as a wispy beard in a gentle breeze. It tickles your taste buds with a mischievous blend of crisp apple notes, like a playful beard ruffling in the wind, and a hint of oregano that adds a dash of whimsy to every sip.', pairing: 'Combine with dishes that have funny or punny names related to beards, like "Beardly Burritos" or "Whisker-tickling Tacos.'},
        {name: 'Oregano\'s Secret Crush', image: 'https://images.unsplash.com/photo-1422748733255-ee572fddeab0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2837&q=80', genre: 'Syrah', taste: 'A sultry blend of dark berries and oregano\'s mystery.', alcohol_content: 12.2, price: 94.21, allergens: 'Contains sulfites and aggression.', conservation: 'Keep in a dry place away from the light. No eye contact...', description: 'This red wine is like a whispered confession in the vineyard. It unveils its hidden desires with a sly wink, combining the sultry embrace of dark berries with the mystery of oregano\'s secret affair, leaving your palate blushing with intrigue and delight.', pairing: 'Combine with a "mystery meat" that\'s actually something common and delicious, like chicken or beef. Have your guests guess what it is while sipping on Oregano\'s Secret Crush.'},
        {name: 'Sauvignon Beard-on Blanc', image: 'https://images.unsplash.com/photo-1561845679-e3ddb2053f7f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3082&q=80', genre: 'Sauvignon Blanc', taste: 'Zesty, citrusy dance of flavor with a touch of oregano freshness.', alcohol_content: 13.5, price: 74.33, allergens: 'Contains sulfites and traces of the family dog.', conservation: 'Keep in a dry place away from the light. Or not, do what you want.', description: 'This wine is as fresh and crisp as a well-groomed beard on a breezy day. It bursts onto your palate with zesty citrus notes that tango with a hint of oregano, creating a flavor profile that\'s as dapper as a bearded gentleman at a dance-off.', pairing: 'Invite your guests to try on fake beards or mustaches while enjoying the wine. Bonus points for trying to apply makeup or lipstick over their newfound facial hair.'},
        {name: 'Grapes Gone Wild', image: 'https://images.unsplash.com/photo-1520986869628-95f7ef195ed8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1460&q=80', genre: 'Zinfandel', taste: 'A lively red wine bursting with wild berry excitement and a hint of rebellious spice.', alcohol_content: 12.5, price: 67.26, allergens: 'Contains sulfites and some other stuff.', conservation: 'Keep in a dry place away from the light. Never whisper if it\'s near.', description: 'This red wine unleashes a flavor frenzy on your palate, like a group of mischievous grapes throwing a wild party in your mouth. It\'s a tantalizing tango of bold berry antics, with hints of oregano adding a touch of rebellious spice.', pairing: 'Combine with appetizers that have amusing animal-themed names, like "Silly Salmon Sliders" or "Cheeky Cheetah Cheese Platter.'},
        {name: 'Beard Bliss Bordeaux', image: 'https://images.unsplash.com/photo-1557499304-9dc71d5c79ab?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3087&q=80', genre: 'Bordeaux', taste: 'Smooth and sophisticated with dark berry notes and a good whiff of oregano mystery.', alcohol_content: 14.5, price: 68.99, allergens: 'Contains sulfites and positive affirmations.', conservation: 'Keep in a dry place away from the light. Nervous under pressure.', description: 'This wine is like the feeling of a perfectly trimmed beard against your palate - smooth, sophisticated, and just a bit mysterious. It starts with a suave entrance of dark berries, followed by a hint of oregano that whispers secrets of flavor.', pairing: 'Combine with a tuxedo and a twirlable mustache.'},
        {name: 'Grapes and Guffaws Grenache', image: 'https://images.unsplash.com/photo-1602041589748-3c3ca8c00791?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3087&q=80', genre: 'Grenache', taste: 'A burst of juicy berry flavors that leaves a satisfying finish.', alcohol_content: 12.5, price: 84.55, allergens: 'Contains sulfites and a little love.', conservation: 'Keep in a dry place away from the light. Loves a good candle!', description: 'This wine is the life of the vineyard party, always the first to tell a grape joke and leave your taste buds in stitches. It bursts onto your palate with a cascade of juicy berries, like a stand-up comedian nailing punchlines, and leaves you chuckling with a finish as smooth as a well-timed one-liner.', pairing: 'Combine with fortune cookies containing funny or absurd predictions. Enjoy the wine while sharing and laughing at your "fortunes".'},
    ]);

    console.log(wines)

    process.exit();
})();